### ISSUE TITLE
IntelliJ IDEA  2021.2 support 

### ISSUE THREAD

**Issue by meiMingle** [MysterAitch/JavaParser-AST-Inspector#132]
Thanks for developing this plugin, it is very useful to me! Are there any plans to support IntelliJ IDEA version 2021.2?

**Comment by MysterAitch** [comment]
@meiMingle -- thank you for your patience here!

v0.5.1 has been uploaded -- assuming the verification checks are fine, it should be available for update/download within the next day or two :+1: 

![image](https://user-images.githubusercontent.com/1537214/133781635-d0686c12-99c3-4d37-80af-73d5ca5b706e.png)
