### ISSUE TITLE
Version 2021.3.* is not currently supported in the official shop

### ISSUE THREAD

**Issue by SummerSec** [MysterAitch/JavaParser-AST-Inspector#213]
**Describe the bug:**

**Steps to reproduce:** 

It seems that the following was not changed to 213.*
![image](https://user-images.githubusercontent.com/47944478/151486213-d57297c9-fe9d-4e05-b0ec-043076bd072a.png)

**Expected behavior:**

**Additional context:**

https://plugins.jetbrains.com/plugin/14245-javaparser-ast-inspector/versions
![image](https://user-images.githubusercontent.com/47944478/151486099-b2cc577e-4e6d-488b-8eac-a237ca853237.png)

**Comment by MysterAitch** [comment]
Let's try that one again! :+1: 

https://github.com/MysterAitch/JavaParser-AST-Inspector/compare/v0.5.2...v0.5.3
