### ISSUE TITLE
Plugin incompatible with latest Intellij

### ISSUE THREAD

**Issue by matozoid** [MysterAitch/JavaParser-AST-Inspector#40]
```
15:38	Plugin Error
			Plugin "JavaParser AST Inspector" is incompatible (until build 201.SNAPSHOT < IC-202.7319.50).
```
:-(

**Comment by MysterAitch** [comment]
On its way shortly :) 

![image](https://user-images.githubusercontent.com/1537214/97619289-f2805a00-1a17-11eb-8f8b-4331e7b7f7ba.png)

**Comment by MysterAitch** [comment]
Done and available for update/download :)

![image](https://user-images.githubusercontent.com/1537214/97724720-2f565a80-1ac5-11eb-9ed7-ef3a3e17a3c2.png)

![image](https://user-images.githubusercontent.com/1537214/97724786-46954800-1ac5-11eb-97ec-e7d366209f60.png)
